name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-18.04
    steps:                                              # <-- must use actions/checkout@v1 before mirroring!
    - uses: mozmeao/checkout@v1
    - uses: mozmeao/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@gitlab.com:mozmeao/aws-cost-monitor-slack-bot.git
        ssh_private_key:                                # <-- use 'secrets' to pass credential information.
          ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
